No. changed back to 'grobner'. This
is a problem.

This directory is called 'mext_grobner'
rather than grobner because otherwise
load(grobner) fails.
